/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adrian' at '10/20/17 8:34 AM' with Gradle 2.13
 *
 * @author adrian, @date 10/20/17 8:34 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
